---
# Cleanup existing cluster resources
- name: Get a list of all virtual machines
  ansible.builtin.command: virsh list --all --name
  register: vms
  changed_when: vms.rc == 0
  become: true

- name: Filter VMs containing 'clustername' in their names
  ansible.builtin.set_fact:
    allvms: "{{ vms.stdout_lines | select('search', clustername) }}"

- name: Destroy all vms
  community.libvirt.virt:
    command: destroy
    force: true
    name: "{{ item }}"
  loop: "{{ allvms }}"
  ignore_errors: true
  become: true

- name: Undefine all vms
  community.libvirt.virt:
    command: undefine
    force: true
    name: "{{ item }}"
  loop: "{{ allvms }}"
  ignore_errors: true
  become: true

- name: Delete all network files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  register: deletefiles
  with_items:
    - "/etc/NetworkManager/dnsmasq.d/{{ clustername }}.conf"
    - "/etc/dnsmasq.{{ clustername }}.addnhosts"
    - "/{{ clusters_dir }}/{{ clustername }}/"
  become: true
